export enum AddMainCategoryActionType {
  ADD_MAIN_CATEGORY_SUCCESS = "ADD_MAIN_CATEGORY_SUCCESS",
  ADD_MAIN_CATEGORY_FAILED = "ADD_MAIN_CATEGORY_FAILED",
  ADD_MAIN_CATEGORY_RESET = "ADD_MAIN_CATEGORY_RESET",
}
