export enum addProductBrand {
    ADD_PRODUCT_BRAND_SUCCESS = "ADD_PRODUCT_BRAND_SUCCESS",
    ADD_PRODUCT_BRAND_FAILED = "ADD_PRODUCT_BRAND_FAILED",
    ADD_PRODUCT_BRAND_RESET = "ADD_PRODUCT_BRAND_RESET",
  }