export enum DeleteProductBrandActionType {
  DELETE_PRODUCT_BRAND_SUCCESS = "DELETE__PRODUCT_BRAND_SUCCESS",
  DELETE__PRODUCT_BRAND_FAILED = "DELETE__PRODUCT_BRAND_FAILED",
  DELETE__PRODUCT_BRAND_RESET = "DELETE__PRODUCT_BRAND_RESET",
}
