export enum DeleteMainCategoryActionType {
    DELETE_MAIN_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS",
    DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED",
    DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET",
  }
  