export enum GetMainCategoryByIdActionType {
  GET_MAIN_CATEGORY_BYID_SUCCESS = "GET_MAIN_CATEGORY_BYID_SUCCESS",
  GET_MAIN_CATEGORY_BYID_FAILED = "GET_MAIN_CATEGORY_BYID_FAILED",
  GET_MAIN_CATEGORY_BYID_RESET = "GET_MAIN_CATEGORY_BYID_RESET",
}
