export enum getProductBrandActionType {
    GET_PRODUCT_BRAND_SUCCESS = "GET_PRODUCT_BRAND_SUCCESS",
    GET_PRODUCT_BRAND_FAILED = "GET_PRODUCT_BRAND_FAILED",
    GET_PRODUCT_BRAND_RESET = "GET_PRODUCT_BRAND_RESET",
  }