export enum GetProductCategoryByID {
    GET_PRODUCT_CATEGORY_BY_ID_SUCCESS = "GET_PRODUCT_CATEGORY_BY_ID_SUCCESS",
    GET_PRODUCT_CATEGORY_BY_ID_FAILED = "GET_PRODUCT_CATEGORY_BY_ID_FAILED",
    GET_PRODUCT_CATEGORY_BY_ID_RESET = "GET_PRODUCT_CATEGORY_BY_ID_RESET",
  }