export enum UpdateMainCategoryActionType {
    UPDATE_MAIN_CATEGORY_SUCCESS = "UPDATE_MAIN_CATEGORY_SUCCESS",
    UPDATE_MAIN_CATEGORY_FAILED = "UPDATE_MAIN_CATEGORY_FAILED",
    UPDATE_MAIN_CATEGORY_RESET = "UPDATE_MAIN_CATEGORY_RESET",
  }
  