export enum UpdateCategoryActionType {
  UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_FAILED = "UPDATE_CATEGORY_FAILED",
  UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET",
}
